ARG PYTHON_VERSION=3.12
ARG OS_VERSION=bookworm
FROM ghcr.io/hoglandets-it/devcontainer-python-mssql:${PYTHON_VERSION}-${OS_VERSION}

RUN pip3 install --no-cache-dir --no-cache beetl infisical-python python-dotenv