on:
  push:
    branches:
      - main
    paths:
      - 'python-mssql/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: beetl
          file: beetl/Dockerfile
          tags: |
            ghcr.io/hoglandets-it/devcontainer-beetl:3.12-bookworm
            ghcr.io/hoglandets-it/devcontainer-beetl:bookworm
            ghcr.io/hoglandets-it/devcontainer-beetl:latest
          push: true
          build-args: |
            PYTHON_VERSION=3.12
            OS_VERSION=bookworm
